name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: fulfil
      run: sudo apt-get install automake
    - name: reconfigure
      run: autoreconf -fi && exec ls -l install-sh
    - name: configure
      run: exec sh -x configure
    - name: make
      run: exec make
    - name: make check
      run: exec make check
    - name: make distcheck
      run: exec make distcheck
